//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using Capa_Entidad;
    
    public partial class VeterinariaEntities : DbContext
    {
        public VeterinariaEntities()
            : base("name=VeterinariaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Mascota> Mascota { get; set; }
        public virtual DbSet<RazaMascota> RazaMascota { get; set; }
        public virtual DbSet<TipoMascota> TipoMascota { get; set; }
    
        public virtual int Proc_actualizarUsuario(Nullable<int> id_Usuario, string nombre_Completo, string direccion, string ciudad, string telefono, string email, string password)
        {
            var id_UsuarioParameter = id_Usuario.HasValue ?
                new ObjectParameter("id_Usuario", id_Usuario) :
                new ObjectParameter("id_Usuario", typeof(int));
    
            var nombre_CompletoParameter = nombre_Completo != null ?
                new ObjectParameter("nombre_Completo", nombre_Completo) :
                new ObjectParameter("nombre_Completo", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("direccion", direccion) :
                new ObjectParameter("direccion", typeof(string));
    
            var ciudadParameter = ciudad != null ?
                new ObjectParameter("ciudad", ciudad) :
                new ObjectParameter("ciudad", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_actualizarUsuario", id_UsuarioParameter, nombre_CompletoParameter, direccionParameter, ciudadParameter, telefonoParameter, emailParameter, passwordParameter);
        }
    
        public virtual int Proc_crearRol(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_crearRol", nombreParameter);
        }
    
        public virtual int Proc_crearRol_Usuario(Nullable<int> id_Rol, Nullable<int> id_Usuario)
        {
            var id_RolParameter = id_Rol.HasValue ?
                new ObjectParameter("id_Rol", id_Rol) :
                new ObjectParameter("id_Rol", typeof(int));
    
            var id_UsuarioParameter = id_Usuario.HasValue ?
                new ObjectParameter("id_Usuario", id_Usuario) :
                new ObjectParameter("id_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_crearRol_Usuario", id_RolParameter, id_UsuarioParameter);
        }
    
        public virtual int Proc_crearUsuario(string nombre_Completo, string direccion, string ciudad, string telefono, string email, string password)
        {
            var nombre_CompletoParameter = nombre_Completo != null ?
                new ObjectParameter("nombre_Completo", nombre_Completo) :
                new ObjectParameter("nombre_Completo", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("direccion", direccion) :
                new ObjectParameter("direccion", typeof(string));
    
            var ciudadParameter = ciudad != null ?
                new ObjectParameter("ciudad", ciudad) :
                new ObjectParameter("ciudad", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_crearUsuario", nombre_CompletoParameter, direccionParameter, ciudadParameter, telefonoParameter, emailParameter, passwordParameter);
        }
    
        public virtual int Proc_eliminarUsuario(Nullable<int> id_Uusuario)
        {
            var id_UusuarioParameter = id_Uusuario.HasValue ?
                new ObjectParameter("id_Uusuario", id_Uusuario) :
                new ObjectParameter("id_Uusuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_eliminarUsuario", id_UusuarioParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Proc_listarid_RolPorid_Usuario(Nullable<int> id_Usuario)
        {
            var id_UsuarioParameter = id_Usuario.HasValue ?
                new ObjectParameter("id_Usuario", id_Usuario) :
                new ObjectParameter("id_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Proc_listarid_RolPorid_Usuario", id_UsuarioParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Proc_listarid_UsuarioPorEmail(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Proc_listarid_UsuarioPorEmail", emailParameter);
        }
    
        public virtual ObjectResult<Proc_listarUsuario_Result> Proc_listarUsuario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_listarUsuario_Result>("Proc_listarUsuario");
        }
    
        public virtual ObjectResult<Proc_listarUsuarioPorid_Usuario_Result> Proc_listarUsuarioPorid_Usuario(Nullable<int> id_Usuario)
        {
            var id_UsuarioParameter = id_Usuario.HasValue ?
                new ObjectParameter("id_Usuario", id_Usuario) :
                new ObjectParameter("id_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_listarUsuarioPorid_Usuario_Result>("Proc_listarUsuarioPorid_Usuario", id_UsuarioParameter);
        }
    
        public virtual ObjectResult<Proc_loguearse_Result> Proc_loguearse(string email, string password)
        {
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_loguearse_Result>("Proc_loguearse", emailParameter, passwordParameter);
        }
    
        public virtual int Proc_actualizarMascota(Nullable<int> id_Mascota, Nullable<int> id_Usuario, Nullable<int> id_Tipo, Nullable<int> id_Raza, string nombre_Completo, string sexo, string peso, byte[] foto, string fecha_Ingreso, string fecha_Modificacion)
        {
            var id_MascotaParameter = id_Mascota.HasValue ?
                new ObjectParameter("id_Mascota", id_Mascota) :
                new ObjectParameter("id_Mascota", typeof(int));
    
            var id_UsuarioParameter = id_Usuario.HasValue ?
                new ObjectParameter("id_Usuario", id_Usuario) :
                new ObjectParameter("id_Usuario", typeof(int));
    
            var id_TipoParameter = id_Tipo.HasValue ?
                new ObjectParameter("id_Tipo", id_Tipo) :
                new ObjectParameter("id_Tipo", typeof(int));
    
            var id_RazaParameter = id_Raza.HasValue ?
                new ObjectParameter("id_Raza", id_Raza) :
                new ObjectParameter("id_Raza", typeof(int));
    
            var nombre_CompletoParameter = nombre_Completo != null ?
                new ObjectParameter("nombre_Completo", nombre_Completo) :
                new ObjectParameter("nombre_Completo", typeof(string));
    
            var sexoParameter = sexo != null ?
                new ObjectParameter("sexo", sexo) :
                new ObjectParameter("sexo", typeof(string));
    
            var pesoParameter = peso != null ?
                new ObjectParameter("peso", peso) :
                new ObjectParameter("peso", typeof(string));
    
            var fotoParameter = foto != null ?
                new ObjectParameter("foto", foto) :
                new ObjectParameter("foto", typeof(byte[]));
    
            var fecha_IngresoParameter = fecha_Ingreso != null ?
                new ObjectParameter("fecha_Ingreso", fecha_Ingreso) :
                new ObjectParameter("fecha_Ingreso", typeof(string));
    
            var fecha_ModificacionParameter = fecha_Modificacion != null ?
                new ObjectParameter("fecha_Modificacion", fecha_Modificacion) :
                new ObjectParameter("fecha_Modificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_actualizarMascota", id_MascotaParameter, id_UsuarioParameter, id_TipoParameter, id_RazaParameter, nombre_CompletoParameter, sexoParameter, pesoParameter, fotoParameter, fecha_IngresoParameter, fecha_ModificacionParameter);
        }
    
        public virtual int Proc_actualizarTipoMascota(Nullable<int> id_Tipo, string tipo)
        {
            var id_TipoParameter = id_Tipo.HasValue ?
                new ObjectParameter("id_Tipo", id_Tipo) :
                new ObjectParameter("id_Tipo", typeof(int));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_actualizarTipoMascota", id_TipoParameter, tipoParameter);
        }
    
        public virtual int Proc_crearMascota(Nullable<int> id_Usuario, Nullable<int> id_Tipo, Nullable<int> id_Raza, string nombre_Completo, string sexo, string peso, byte[] foto, string fecha_Ingreso, string fecha_Modificacion)
        {
            var id_UsuarioParameter = id_Usuario.HasValue ?
                new ObjectParameter("id_Usuario", id_Usuario) :
                new ObjectParameter("id_Usuario", typeof(int));
    
            var id_TipoParameter = id_Tipo.HasValue ?
                new ObjectParameter("id_Tipo", id_Tipo) :
                new ObjectParameter("id_Tipo", typeof(int));
    
            var id_RazaParameter = id_Raza.HasValue ?
                new ObjectParameter("id_Raza", id_Raza) :
                new ObjectParameter("id_Raza", typeof(int));
    
            var nombre_CompletoParameter = nombre_Completo != null ?
                new ObjectParameter("nombre_Completo", nombre_Completo) :
                new ObjectParameter("nombre_Completo", typeof(string));
    
            var sexoParameter = sexo != null ?
                new ObjectParameter("sexo", sexo) :
                new ObjectParameter("sexo", typeof(string));
    
            var pesoParameter = peso != null ?
                new ObjectParameter("peso", peso) :
                new ObjectParameter("peso", typeof(string));
    
            var fotoParameter = foto != null ?
                new ObjectParameter("foto", foto) :
                new ObjectParameter("foto", typeof(byte[]));
    
            var fecha_IngresoParameter = fecha_Ingreso != null ?
                new ObjectParameter("fecha_Ingreso", fecha_Ingreso) :
                new ObjectParameter("fecha_Ingreso", typeof(string));
    
            var fecha_ModificacionParameter = fecha_Modificacion != null ?
                new ObjectParameter("fecha_Modificacion", fecha_Modificacion) :
                new ObjectParameter("fecha_Modificacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_crearMascota", id_UsuarioParameter, id_TipoParameter, id_RazaParameter, nombre_CompletoParameter, sexoParameter, pesoParameter, fotoParameter, fecha_IngresoParameter, fecha_ModificacionParameter);
        }
    
        public virtual int Proc_crearRazaMascota(string raza)
        {
            var razaParameter = raza != null ?
                new ObjectParameter("raza", raza) :
                new ObjectParameter("raza", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_crearRazaMascota", razaParameter);
        }
    
        public virtual int Proc_crearTipoMascota(string tipo)
        {
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_crearTipoMascota", tipoParameter);
        }
    
        public virtual int Proc_eliminarMascota(Nullable<int> id_Mascota)
        {
            var id_MascotaParameter = id_Mascota.HasValue ?
                new ObjectParameter("id_Mascota", id_Mascota) :
                new ObjectParameter("id_Mascota", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_eliminarMascota", id_MascotaParameter);
        }
    
        public virtual int Proc_eliminarRazaMascota(Nullable<int> id_raza)
        {
            var id_razaParameter = id_raza.HasValue ?
                new ObjectParameter("id_raza", id_raza) :
                new ObjectParameter("id_raza", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_eliminarRazaMascota", id_razaParameter);
        }
    
        public virtual int Proc_eliminarTipoMascota(Nullable<int> id_Tipo)
        {
            var id_TipoParameter = id_Tipo.HasValue ?
                new ObjectParameter("id_Tipo", id_Tipo) :
                new ObjectParameter("id_Tipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_eliminarTipoMascota", id_TipoParameter);
        }
    
        public virtual ObjectResult<Proc_listarMascota_Result> Proc_listarMascota()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_listarMascota_Result>("Proc_listarMascota");
        }
    
        public virtual ObjectResult<Proc_listarMascotaPorid_Mascota_Result> Proc_listarMascotaPorid_Mascota(Nullable<int> id_Mascota)
        {
            var id_MascotaParameter = id_Mascota.HasValue ?
                new ObjectParameter("id_Mascota", id_Mascota) :
                new ObjectParameter("id_Mascota", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_listarMascotaPorid_Mascota_Result>("Proc_listarMascotaPorid_Mascota", id_MascotaParameter);
        }
    
        public virtual ObjectResult<Proc_listarRazaMascota_Result> Proc_listarRazaMascota()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_listarRazaMascota_Result>("Proc_listarRazaMascota");
        }
    
        public virtual ObjectResult<Proc_listarRazaMascotaPorid_Raza_Result> Proc_listarRazaMascotaPorid_Raza(Nullable<int> id_Raza)
        {
            var id_RazaParameter = id_Raza.HasValue ?
                new ObjectParameter("id_Raza", id_Raza) :
                new ObjectParameter("id_Raza", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_listarRazaMascotaPorid_Raza_Result>("Proc_listarRazaMascotaPorid_Raza", id_RazaParameter);
        }
    
        public virtual ObjectResult<Proc_listarTipoMascota_Result> Proc_listarTipoMascota()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_listarTipoMascota_Result>("Proc_listarTipoMascota");
        }
    
        public virtual ObjectResult<Proc_listarTipoMascotaPorid_Tipo_Result> Proc_listarTipoMascotaPorid_Tipo(Nullable<int> id_Tipo)
        {
            var id_TipoParameter = id_Tipo.HasValue ?
                new ObjectParameter("id_Tipo", id_Tipo) :
                new ObjectParameter("id_Tipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_listarTipoMascotaPorid_Tipo_Result>("Proc_listarTipoMascotaPorid_Tipo", id_TipoParameter);
        }
    
        public virtual int Proc_actualizarRazaMascota(Nullable<int> id_raza, string raza)
        {
            var id_razaParameter = id_raza.HasValue ?
                new ObjectParameter("id_raza", id_raza) :
                new ObjectParameter("id_raza", typeof(int));
    
            var razaParameter = raza != null ?
                new ObjectParameter("raza", raza) :
                new ObjectParameter("raza", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_actualizarRazaMascota", id_razaParameter, razaParameter);
        }
    }
}
