//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita_Usuario
    {
        public int id_Cita { get; set; }
        public int id_Usuario { get; set; }
        public int id_Mascota { get; set; }
        public int id_UsuarioVeterinario { get; set; }
    
        public virtual Cita Cita { get; set; }
        public virtual Mascota Mascota { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
