//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consejo
    {
        public int id_Consejo { get; set; }
        public int id_Tipo { get; set; }
        public int id_Raza { get; set; }
        public string descripcion { get; set; }
    
        public virtual RazaMascota RazaMascota { get; set; }
        public virtual TipoMascota TipoMascota { get; set; }
    }
}
