//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mascota
    {
        public Mascota()
        {
            this.Cita_Usuario = new HashSet<Cita_Usuario>();
            this.Mascota_Usuario = new HashSet<Mascota_Usuario>();
        }
    
        public int id_Mascota { get; set; }
        public string nombre_Completo { get; set; }
        public string sexo { get; set; }
        public string peso { get; set; }
        public byte[] foto { get; set; }
        public string fecha_Ingreso { get; set; }
        public string fecha_Modificacion { get; set; }
    
        public virtual ICollection<Cita_Usuario> Cita_Usuario { get; set; }
        public virtual ICollection<Mascota_Usuario> Mascota_Usuario { get; set; }
    }
}
