//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class RazaMascota
    {
        public RazaMascota()
        {
            this.Mascota = new HashSet<Mascota>();
        }
    
        public int id_Raza { get; set; }
        public string raza { get; set; }
    
        public virtual ICollection<Mascota> Mascota { get; set; }
    }
}
