//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoMascota
    {
        public TipoMascota()
        {
            this.Consejo = new HashSet<Consejo>();
            this.Mascota_Usuario = new HashSet<Mascota_Usuario>();
        }
    
        public int id_Tipo { get; set; }
        public string tipo { get; set; }
    
        public virtual ICollection<Consejo> Consejo { get; set; }
        public virtual ICollection<Mascota_Usuario> Mascota_Usuario { get; set; }
    }
}
