//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Rol = new HashSet<Rol>();
            this.Mascota = new HashSet<Mascota>();
        }
    
        public int id_Usuario { get; set; }
        public string nombre_Completo { get; set; }
        public string direccion { get; set; }
        public string ciudad { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<Rol> Rol { get; set; }
        public virtual ICollection<Mascota> Mascota { get; set; }
    }
}
